const products = [
  { id: "1", name: "IPhone 11", quantity: 15, category: "Electronik" },
  { id: "2", name: "LG TV", quantity: 44, category: "Electronik" },
  { id: "3", name: "Adidas ayakkabi", quantity: 44, category: "Giyim" },
  { id: "4", name: "Logitech Mouse", quantity: 2, category: "Elektronik" },
  { id: "5", name: "Somon Baligi", quantity: 105, category: "Besin" },
  { id: "6", name: "Futbol Topu", quantity: 99, category: "Spor" },
  { id: "7", name: "Yacht", quantity: 1, category: "Tasit" },
  { id: "8", name: "Tesla category Y", quantity: 777, category: "Tasit" },
  { id: "9", name: "Kalkan Baligi", quantity: 105, category: "Besin" },
  { id: "10", name: "Tenis Topu", quantity: 99, category: "Spor" },
  { id: "11", name: "Gitar", quantity: 1, category: "Aksesuar" },
  { id: "12", name: "Peçete", quantity: 777, category: "Eşya" },
];

export default products;

// const products = [
//   {
//     id: 1,
//     name: "Laptop",
//     category: "Electronics",
//     quantity: 15,
//     price: 1500,
//     supplier: "TechSupply Co.",
//     status: "In Stock",
//   },
//   {
//     id: 2,
//     name: "Wireless Mouse",
//     category: "Accessories",
//     quantity: 50,
//     price: 20,
//     supplier: "GadgetWorld",
//     status: "In Stock",
//   },
//   {
//     id: 3,
//     name: "Mechanical Keyboard",
//     category: "Accessories",
//     quantity: 30,
//     price: 100,
//     supplier: "Keyboard Masters",
//     status: "In Stock",
//   },
//   {
//     id: 4,
//     name: "LED Monitor",
//     category: "Electronics",
//     quantity: 10,
//     price: 300,
//     supplier: "Display Solutions",
//     status: "In Stock",
//   },
//   {
//     id: 5,
//     name: "Smartphone",
//     category: "Electronics",
//     quantity: 25,
//     price: 800,
//     supplier: "MobileX Inc.",
//     status: "In Stock",
//   },
//   {
//     id: 6,
//     name: "Bluetooth Headphones",
//     category: "Accessories",
//     quantity: 40,
//     price: 75,
//     supplier: "AudioGear",
//     status: "In Stock",
//   },
//   {
//     id: 7,
//     name: "Gaming Chair",
//     category: "Furniture",
//     quantity: 12,
//     price: 250,
//     supplier: "Comfort Zone",
//     status: "In Stock",
//   },
//   {
//     id: 8,
//     name: "External Hard Drive",
//     category: "Storage",
//     quantity: 35,
//     price: 120,
//     supplier: "StorageKing",
//     status: "In Stock",
//   },
//   {
//     id: 9,
//     name: "USB-C Adapter",
//     category: "Accessories",
//     quantity: 75,
//     price: 15,
//     supplier: "Tech Hub",
//     status: "In Stock",
//   },
//   {
//     id: 10,
//     name: "Desk Lamp",
//     category: "Furniture",
//     quantity: 20,
//     price: 45,
//     supplier: "Lightify",
//     status: "In Stock",
//   },
//   {
//     id: 11,
//     name: "Tablet",
//     category: "Electronics",
//     quantity: 18,
//     price: 600,
//     supplier: "TabTech",
//     status: "In Stock",
//   },
//   {
//     id: 12,
//     name: "Printer",
//     category: "Office Supplies",
//     quantity: 8,
//     price: 150,
//     supplier: "PrintPro",
//     status: "In Stock",
//   },
//   {
//     id: 13,
//     name: "Router",
//     category: "Networking",
//     quantity: 22,
//     price: 80,
//     supplier: "NetConnect",
//     status: "In Stock",
//   },
//   {
//     id: 14,
//     name: "HD Webcam",
//     category: "Accessories",
//     quantity: 16,
//     price: 60,
//     supplier: "CaptureVision",
//     status: "In Stock",
//   },
//   {
//     id: 15,
//     name: "Office Chair",
//     category: "Furniture",
//     quantity: 10,
//     price: 200,
//     supplier: "Office Comfort",
//     status: "In Stock",
//   },
// ];

// export default products;
